# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_auto_20170228_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_number',
            field=models.CharField(max_length=10, verbose_name='工号'),
        ),
    ]
